### ISSUE TITLE
Configurable gradient length

### ISSUE THREAD

**Issue by dkasak** [corollari/waspline-reader#1]
The Beeline Reader gradient seems to start much earlier in the line than in Waspline Reader. For instance, in red lines, I can detect colour change as early as 1/3rd or 1/4th into the line. I think this works a bit better than the Waspline current setting, especially for longer lines.

I saw the `GRADIENT_LENGTH_PERCENTAGE` const in the code which seems to control this aspect. Could this be exposed as a setting in Waspline Reader's config page?

Thank you for the awesome extension!

**Comment by corollari** [comment]
Great idea! I'll implement it right away.
Thanks for the feedback :smiley:

**Comment by corollari** [comment]
Just published a new version with the changes, should be available in a few hours!

**Comment by dkasak** [comment]
Thanks, that was quick!

The extension has been updated to 1.1.0 for me now, but I can't seem to find how to change this setting. There don't seem to be any options on Waspline Reader's page in the Add-ons Manager. Am I missing something?

**Comment by corollari** [comment]
The settings page wasn't working properly due to an inconsistency between the firefox and chrome's APIs. I just fixed it and published a new version. Thanks for noticing!

**Comment by dkasak** [comment]
Works great, thanks!
